services:
  - type: web
    name: revcdos
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py --port $PORT --packed https://folder.morgen.qzz.io/revcdos.bin
    healthCheckPath: /healthz
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
